import React  from "react";
import "~/styles/fonts.css";
import MainLayout from "~/app/_components/MainLayout";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{overflowX: 'hidden'}}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
